packages:
  - "apps/*"
  - "packages/common/*"
  - "packages/features/*"

catalog:
  "@eslint/eslintrc": "^3"
  "@tailwindcss/postcss": "^4.0.0"
  "@types/file-saver": "^2.0.7"
  "@types/js-cookie": "^3.0.6"
  "@types/lodash-es": "^4.17.12"
  "@types/node": "^22.10.5"
  "@types/qs": "^6.9.17"
  "@types/react": "19.0.2"
  "@types/react-dom": "19.0.2"
  "axios": "^1.7.9"
  "date-fns": "4.1.0"
  "eslint": "^9"
  "eslint-config-next": "15.2.2"
  "file-saver": "^2.0.5"
  "js-cookie": "^3.0.5"
  "lodash-es": "^4.17.21"
  "next": "15.2.2"
  "next-themes": "^0.4.3"
  "prettier": "^3.4.2"
  "qs": "^6.13.1"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "react-hook-form": "^7.54.2"
  "tailwindcss": "^4.0.0"
  "tailwindcss-animate": "^1.0.7"
  "turbo": "^2.3.3"
  "typescript": "^5.7.2"
  "zustand": "^5.0.3"
