packages:
  - "apps/*"
  - "packages/common/*"
  - "packages/features/*"

catalog:
  "@eslint/eslintrc": "^3"
  "@tailwindcss/postcss": "^4.0.0"
  "@types/file-saver": "^2.0.7"
  "@types/js-cookie": "^3.0.6"
  "@types/lodash-es": "^4.17.12"
  "@types/node": "^24.10.1"
  "@types/qs": "^6.9.17"
  "@types/react": "19.0.2"
  "@types/react-dom": "19.0.2"
  "@types/negotiator": "^0.6.3"
  "@formatjs/intl-localematcher": "^0.6.0"
  "@tanstack/react-table": "^8.21.2"
  "@vercel/analytics": "^1.5.0"
  "axios": "^1.7.9"
  "clsx": "^2.1.1"
  "date-fns": "4.1.0"
  "eslint": "^9"
  "eslint-config-next": "^16.0.3"
  "eslint-config-prettier": "^10.1.8"
  "eslint-plugin-only-warn": "^1.0.3"
  "eslint-plugin-prettier": "^5.2.1"
  "eslint-plugin-turbo": "^2.3.3"
  "file-saver": "^2.0.5"
  "js-cookie": "^3.0.5"
  "lodash-es": "^4.17.21"
  "next": "^16.0.3"
  "next-auth": "^4.24.13"
  "next-themes": "^0.4.3"
  "next-intl": "^4.5.5"
  "negotiator": "^1.0.0"
  "prettier": "^3.4.2"
  "qs": "^6.13.1"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "react-hook-form": "^7.54.2"
  "tailwindcss": "^4.0.0"
  "tailwindcss-animate": "^1.0.7"
  "turbo": "^2.3.3"
  "typescript": "^5.7.2"
  "zustand": "^5.0.3"
  "husky": "^9.1.7"
  "lint-staged": "^16.2.7"
  "prettier-plugin-tailwindcss": "^0.7.1"
