packages:
  - "apps/*"
  - "packages/common/*"
  - "packages/features/*"

catalog:
  "@types/node": "^22.10.5"
  "@types/react": "19.0.2"
  "@types/react-dom": "19.0.2"
  "@tailwindcss/postcss": "^4.0.0"
  "next": "15.2.0-canary.74"
  "next-themes": "^0.4.3"
  "prettier": "^3.4.2"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "turbo": "^2.3.3"
  "tailwindcss": "^4.0.0"
  "typescript": "^5.7.2"
