packages:
  - "apps/*"
  - "packages/common/*"

catalog:
  "@next/eslint-plugin-next": "^15.1.0"
  "@radix-ui/react-slot": "^1.1.1"
  "@turbo/gen": "^2.2.3"
  "@types/node": "^22.9.0"
  "@types/react": "19.0.2"
  "@types/react-dom": "19.0.2"
  "@typescript-eslint/eslint-plugin": "^8.15.0"
  "@typescript-eslint/parser": "^8.15.0"
  "autoprefixer": "^10.4.20"
  "class-variance-authority": "^0.7.0"
  "clsx": "^2.1.1"
  "eslint": "^9.15.0"
  "eslint-config-prettier": "^9.1.0"
  "eslint-plugin-only-warn": "^1.1.0"
  "eslint-plugin-react": "^7.37.2"
  "eslint-plugin-react-hooks": "^5.0.0"
  "eslint-plugin-turbo": "^2.3.0"
  "globals": "^15.12.0"
  "lucide-react": "0.469.0"
  "next": "^15.1.0"
  "next-themes": "^0.4.3"
  "postcss": "^8.4.47"
  "react": "^19.0.0"
  "react-dom": "^19.0.0"
  "tailwind-merge": "^2.5.4"
  "tailwindcss": "^3.4.14"
  "tailwindcss-animate": "^1.0.7"
  "typescript": "^5.6.3"
  "typescript-eslint": "^8.15.0"
  "zod": "^3.23.8"
